# Generated by Django 4.1.3 on 2022-11-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text1',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
